### Goal save - routine : 1(Every Day)
POST localhost:7777/api/bigGoal
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
    "title" : "test title1111",
    "contents" : "test contents11111",
    "icon" : "icon♥️11111",
    "endDate" : "2024-01-06",
    "shareStatus" : 0,
    "completeStatus" : 0,
    "ruleReqDto" :
    {
        "routine" : 1,
        "timeAt" : "18:12",
        "contents" : "test contents11111"
    }

}


### Goal save - routin : 2(Weekly)
POST localhost:7777/api/bigGoal
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title22222",
  "contents" : "test contents222222",
  "icon" : "icon♥️",
  "endDate" : "2024-01-06",
  "shareStatus" : 0,
  "completeStatus" : 0,
  "ruleReqDto" :
  {
    "routine" : 2,
    "timeAt" : "18:12",
    "contents" : "test contents222222",
    "ruleRepeatList" :
      [
        1,
        2,
        3
      ]
  }

}


### Goal save - routin : 3(Monthly)
POST localhost:7777/api/bigGoal
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title333333",
  "contents" : "test contents333333",
  "icon" : "icon♥️",
  "endDate" : "2024-01-06",
  "shareStatus" : 0,
  "completeStatus" : 0,
  "ruleReqDto" :
  {
    "routine" : 3,
    "timeAt" : "18:12",
    "contents" : "test contents333333",
    "ruleRepeatList" :
    [
      1,
      2,
      -1
    ]
  }

}


### Goal update - routin 1 -> 2
PUT localhost:7777/api/bigGoal/1
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title1To2",
  "contents" : "test contents1To2",
  "icon" : "icon♥️",
  "endDate" : "2024-01-06",
  "shareStatus" : 1,
  "completeStatus" : 1,
  "ruleReqDto" :
  {
    "routine" : 2,
    "timeAt" : "18:14",
    "contents" : "test contents1To2",
    "ruleRepeatList" :
    [
      10,
      20,
      30
    ]
  }

}
### Goal update - routin 1 -> 3
PUT localhost:7777/api/bigGoal/4
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title1To3",
  "contents" : "test contents1To3",
  "icon" : "icon♥️",
  "endDate" : "2024-01-06",
  "shareStatus" : 1,
  "completeStatus" : 1,
  "ruleReqDto" :
  {
    "routine" : 2,
    "timeAt" : "18:14",
    "contents" : "test contents1To3",
    "ruleRepeatList" :
    [
      11,
      21,
      -1
    ]
  }

}

### Goal update - routin 2 -> 1
PUT localhost:7777/api/bigGoal/2
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title2To1",
  "contents" : "test contents2To1",
  "icon" : "icon♥️2to1",
  "endDate" : "2024-01-06",
  "shareStatus" : 1,
  "completeStatus" : 1,
  "ruleReqDto" :
  {
    "routine" : 1,
    "timeAt" : "18:21",
    "contents" : "test contents2To1"
  }

}

### Goal update - routin 2 -> 3
PUT localhost:7777/api/bigGoal/5
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title2To3",
  "contents" : "test contents2To3",
  "icon" : "icon♥️2to3",
  "endDate" : "2024-01-06",
  "shareStatus" : 1,
  "completeStatus" : 1,
  "ruleReqDto" :
  {
    "routine" : 3,
    "timeAt" : "18:21",
    "contents" : "test contents2To3",
    "ruleRepeatList" :
    [
      111,
      211,
      -11
    ]
  }

}

### Goal update - routin 3 -> 1
PUT localhost:7777/api/bigGoal/3
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title3To1",
  "contents" : "test contents3To1",
  "icon" : "icon♥️3to1",
  "endDate" : "2024-01-06",
  "shareStatus" : 1,
  "completeStatus" : 1,
  "ruleReqDto" :
  {
    "routine" : 1,
    "timeAt" : "18:21",
    "contents" : "test contents3To1"
  }

}

### Goal update - routin 3 -> 2
PUT localhost:7777/api/bigGoal/1
Content-Type: application/json
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}

{
  "title" : "test title3To2",
  "contents" : "test contents3To2",
  "icon" : "icon♥️3to2",
  "endDate" : "2024-01-06",
  "shareStatus" : 1,
  "completeStatus" : 1,
  "ruleReqDto" :
  {
    "routine" : 2,
    "timeAt" : "18:21",
    "contents" : "test contents3To2",
    "ruleRepeatList" :
    [
      11,
      21,
      -1
    ]
  }

}



### Goal Delete
DELETE localhost:7777/api/bigGoal/1
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}


### Goal Update ShareState
PUT localhost:7777/api/bigGoal/share/2
Authorization: {{Authorization}}
refresh_token: {{refresh_token}}