server:
  port: 7777

spring:
  thymeleaf:
    cache: false
  profiles:
    include:
#      - real
#      - oauth
      - local
      - local-oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher